Added option for local sync.

diff --git a/bin/ae-push-web b/bin/ae-push-web
--- a/bin/ae-push-web
+++ b/bin/ae-push-web
@@ -9,6 +9,7 @@ RSYNC_OPTS="-rvlt"
 
 # options
 GROUP=web
+LOCAL=
 DRY=
 HELP=
 
@@ -16,6 +17,7 @@ while getopts "hg:n" option; do
   case "$option" in
   h) HELP=1 ;;
   g) GROUP="$OPTARG" ;;
+  l) LOCAL=1 ;;
   n) DRY=1 ;;
   esac
 done
@@ -26,6 +28,7 @@ if [[ $HELP || ! $1 ]]; then
   echo "usage: $(basename $0) [options] remote_directory"
   echo "  -h         Display this message."
   echo "  -g         EC2 security group of instances."
+  echo "  -l         Sync is done to a local directory."
   echo "  -n         Dry rsync run. Just test."
   exit 1
 fi
@@ -40,18 +43,6 @@ fi
 # remove any trailing /
 remote_directory="${remote_directory%/}"
 
-hosts=$(rudy-ec2 -f tsv instances -g $GROUP | awk '$8 ~ /./ { print $8 }')
-
-if [[ $? -gt 0 ]]; then
-  echo "failed to get web instances"
-  exit $?
-fi
-
-if [[ "x${hosts[0]}" == "x" ]]; then
-  echo "there are no instance in $GROUP"
-  exit 2
-fi
-
 # setup rsync options
 
 # use any file called ".aether_sync_excludes" in the current directory
@@ -65,7 +56,24 @@ if [[ $DRY ]]; then
   RSYNC_OPTS="$RSYNC_OPTS --dry-run"
 fi
 
-# perform sync to each web host
-for host in $hosts; do
-  rsync $RSYNC_OPTS ./ $host:$remote_directory/
-done
+if [[ $LOCAL ]]; then
+  # perform local sync
+  rsync $RSYNC_OPTS ./ "$remote_directory"
+else
+  # perform sync to each web host
+  hosts=$(rudy-ec2 -f tsv instances -g $GROUP | awk '$8 ~ /./ { print $8 }')
+
+  if [[ $? -gt 0 ]]; then
+    echo "failed to get web instances"
+    exit $?
+  fi
+
+  if [[ "x${hosts[0]}" == "x" ]]; then
+    echo "there are no instance in $GROUP"
+    exit 2
+  fi
+
+  for host in $hosts; do
+    rsync $RSYNC_OPTS ./ $host:$remote_directory/
+  done
+fi
